cost=input("enter the cost of the order:")
#total_cost=float(int(cost)*10/100)
total_cost=(f"{int(cost)*10/100}")
print(f"the total cost: {total_cost}")
print('----------------------\n example 2:')
money=input('enter the amount of money')
chidren=input('enter the amount of children')
curncy=input('enter the curncy')
result=(f'{int(money)/int(chidren)}')
print(f'each one shold get{result}{curncy} ')
print("---------------- example 3")
name=input('Name:                ')
print(f"welcom majd at the cours your name is {len(name)} long charter")